import pandas as pd, os

# ── Round 1 data (unchanged) ──────────────────────────────────────────
SOFT_TOXIC = [
    # dismissive / condescending
    "you clearly have no idea what you're talking about",
    "this is embarrassing for you",
    "you should probably stop talking",
    "this makes you look clueless",
    "this might be the worst comment here",
    "this is such a bad take",
    "nobody asked for your opinion",
    "you sound completely brain dead",
    "how do you function in daily life",
    "this comment aged like milk",
    "the sheer audacity of this take",
    "this is painful to read",
    "that is genuinely the dumbest thing i have read today",
    "please stop embarrassing yourself",
    "you are not as smart as you think",
    "maybe think before you type next time",
    "this take is so wrong it hurts",
    "i can feel myself getting dumber reading this",
    "the amount of confidence you have for being so wrong",
    "you might want to do some research before commenting",
    "just stop talking you clearly know nothing",
    "the ignorance in this comment is astounding",
    "wow you really are clueless",
    "this is why people do not take you seriously",
    "absolutely baffling that someone thinks this",
    "you are the problem with this community",
    "this comment should be deleted",
    "please think before you speak",
    "what a completely ignorant take",
    "you are really out here embarrassing yourself",
    "i genuinely cannot believe someone thinks this",
    "you have no clue what you are talking about",
    "this person has never had an original thought",
    "how are you this confidently wrong",
    "every single thing you said is wrong",
    "this is exactly the kind of comment that lowers the IQ of the room",
    "you are wasting everyone's time with this",
    "nobody wants to hear this",
    "go educate yourself before commenting",
    "seriously just stop",
    "you are talking out of nowhere",
    "this might be the worst hot take i have ever seen",
    "just delete this comment please",
    "the lack of self awareness here is staggering",
    "what a completely useless opinion",
    "you are so confidently incorrect",
    "this is why no one takes you seriously",
    "you are embarrassing yourself in front of everyone",
    "i almost feel bad for how wrong you are",
    "no one wants to hear your uninformed opinion",
    "your opinion contributes nothing",
    "just here to let you know this was a terrible comment",
    "you clearly do not understand the topic",
    "how did you come to such a wrong conclusion",
    "please do not comment if you do not know what you are talking about",
    "this take is absolutely terrible",
    "you are making yourself look foolish",
    "this is not the thoughtful commentary anyone was looking for",
    "you are very confidently wrong",
    "what a shallow and uninformed perspective",
    "this is giving me secondhand embarrassment",
    "you really said all of this out loud",
    "your credibility is non existent",
    "you sound like you have never spoken to another human being",
    "i wonder if you even read what you wrote",
    "you are the reason comment sections are terrible",
    "this is among the worst takes on this topic",
    "it shows how little you know about this",
    "the fact that you believe this concerns me",
    "you should reconsider everything you just said",
    "this is peak ignorance right here",
    "how can someone be this confidently wrong",
    "every word of this is a mistake",
    "this comment reveals a lot about you and not in a good way",
    "this is genuinely sad to read",
    "you typed all that and thought it was a good idea",
    "you need to seriously reconsider your talking points",
    "you clearly have not thought this through",
    "this is not the slam dunk you think it is",
    "you are talking to yourself at this point",
    "stop humiliating yourself",
    "you are just contributing noise",
    "what a completely pointless comment",
    "your logic is all over the place",
    "this comment is an embarrassment",
    "wow you really did not think before typing that",
    "this argument has so many holes it is almost impressive",
    "you clearly lack basic understanding",
    "people like you make this platform worse",
    "you are so far off base it is actually funny",
    "just mute yourself for everyone's sake",
    "your reading comprehension is seriously lacking",
    "this is genuinely difficult to read because of how wrong it is",
    "you barely understand what you are commenting on",
    "this tells me everything about your critical thinking ability",
    "you reached a wrong conclusion with full confidence",
    "this is exactly what ignorance looks like in action",
    "please learn the topic before commenting",
    "this might be the most ill-informed comment in this thread",
    "you are just talking to hear yourself at this point",
    "does it bother you being this wrong",
    "please close the tab and log off",
    "you were so confident and so incorrect",
    "nobody here agrees with you and for good reason",
    "your whole argument falls apart immediately",
    "this is honestly hard to take seriously",
    "you really showed everyone your ignorance with this one",
    "this comment is a gift to no one",
    "how long did it take you to come up with something this wrong",
    "the lack of thought here is breathtaking",
    "even a child understands this better than you do",
    "you proved nothing except how misinformed you are",
    "you are speaking with zero knowledge on the subject",
    "this is so wrong it looped back around to being funny",
    "you should be embarrassed by this comment",
    "no one here is going to validate this take",
    "you are completely out of your depth here",
    "this is pure nonsense",
    "just do not comment if this is what you bring to the discussion",
    "you are not adding anything meaningful to this conversation",
    "how does it feel to be this confidently wrong",
    "you are not impressing anyone",
    "this is exactly the kind of content no one needs",
    "your argument has zero substance",
    "you are spectacularly wrong about this",
    "what a colossal waste of words",
    "you tried and failed miserably",
    "you are just making yourself look bad",
    "this take is not even close to being right",
    "you should think twice before sharing opinions this bad",
    "this whole comment is off base",
    "you have added nothing useful to this discussion",
    "the confidence in this comment is unearned",
    "you are struggling to understand the basic point here",
    "this is a deeply uninformed view",
    "you are clearly just here to argue with no actual knowledge",
    "please do not embarrass yourself further",
    "i hope you cringe at this comment later",
    "what a thoroughly bad argument",
    "stepping away from this conversation would benefit everyone",
    "your entire reasoning is flawed",
    "you have completely missed the point",
    "people like you need to listen more and talk less",
    "you are out of your league in this conversation",
    "nobody is taking this comment seriously",
    "this is giving braindead energy",
    "you really thought this was a good point",
    "this contributes nothing and says everything about you",
    "how has no one told you to stop yet",
    "you are just wrong and confidently so",
    "log off and touch some grass",
    "this comment belongs in a time capsule of bad opinions",
    "literally no one agrees with you here",
    "you display a shocking lack of awareness",
    "you are deeply and completely wrong on every point",
    "this is not the gotcha you were hoping for",
    "you need to sit this conversation out",
    "your reasoning is circular and wrong",
    "this whole argument is built on misunderstanding",
    "you are making things worse by speaking",
    "i cannot believe someone is this wrong and this sure of themselves",
    "you need to learn how to think critically",
    "this is genuinely embarrassing to witness",
    "stop typing and start reading",
    "not a single thing you said makes sense",
    "you are proof that confidence and knowledge are not the same thing",
    "this is genuinely one of the worst comments i have seen today",
    "how are you so wrong about something so simple",
    "you typed this out and felt proud",
    "this is a masterclass in missing the point",
    "you need to seriously rethink this",
    "i am struggling to understand how you got to this conclusion",
    "this comment is everything wrong with online discourse",
    "just sit this one out",
    "you are talking yourself in circles",
    "your argument is embarrassingly weak",
    "you are not helping yourself at all here",
    "this ranks among the worst contributions to this thread",
    "you are wrong and everyone can see it",
    "just stop before you embarrass yourself further",
    "no critical thinking happened before this was posted",
    "this is not the flex you think it is",
    "i can not take this comment seriously and neither can anyone else",
    "you are ruining the conversation",
    "this was painful to read",
    "how has no one corrected you before",
    "this comment shows a complete failure to understand the topic",
    "truly an abysmal response",
    "you clearly do not understand what is being discussed",
    "you are the weakest argument in this entire thread",
    "do everyone a favor and think before you post",
    "you should be mortified by this take",
    "this is such sloppy thinking",
    "what a colossal failure of an argument",
    "this is so far off it loops back around to being funny",
    # short sharp ones
    "just embarrassing",
    "this is painful",
    "please stop",
    "absolutely clueless",
    "spectacularly wrong",
    "thoroughly unconvincing",
    "this is not it",
    "completely off base",
    "beyond embarrassing",
    "this take is terrible",
    "not a single brain cell used here",
    "you have no idea",
    "this is genuinely awful",
    "certified braindead take",
    "this reeks of ignorance",
    "you are simply wrong",
    "what a waste of a comment",
    "nobody asked",
    "this is cringeworthy",
    "delete this",
    "sounds clueless",
    "laughably wrong",
    "you missed the entire point",
    "how embarrassing for you",
    "what a terrible argument",
    "the ignorance is unreal",
    "this logic does not logic",
    "no one agrees with you",
    "stop embarrassing yourself",
    "genuinely bad take",
    "you are completely off",
    "this is so bad",
]

# ── Non-toxic — critical but civil ───────────────────────────────────
SOFT_NONTOXIC = [
    "I respectfully disagree with your point",
    "I think you may have misunderstood the argument",
    "This is an interesting perspective but I see it differently",
    "I disagree but I can see where you are coming from",
    "That conclusion seems a stretch given the evidence",
    "I think there is more nuance here than you are giving it credit for",
    "Could you elaborate on why you think that",
    "I am not sure that is entirely accurate",
    "Your reasoning seems a bit off here",
    "I do not think that comparison holds up",
    "That is a debatable point",
    "I think we are looking at this from completely different angles",
    "There is some good points here but also some I disagree with",
    "This seems like an oversimplification",
    "I would push back on that a little",
    "That framing might not be quite right",
    "I think you may be missing some context here",
    "That is an interesting but flawed argument",
    "I do not find that argument convincing",
    "I disagree with the premise of this",
    "The logic here has some gaps",
    "I think the evidence points in a different direction",
    "This is a commonly held but mistaken idea",
    "I think you are conflating two different things",
    "That does not follow from what was said",
    "This argument has been addressed many times",
    "Not sure where you got that information",
    "This analysis misses a few key points",
    "I would recommend looking into this a bit more",
    "I understand your point but I still disagree",
    "This is not my experience at all",
    "I am skeptical of this claim",
    "That conclusion is not well supported here",
    "This view is not widely held for good reason",
    "I think you are jumping to conclusions",
    "There is more to this story",
    "This argument does not quite work",
    "You might want to reconsider this",
    "I think this position is hard to defend",
    "That is not how it typically works",
    "Your sources might be worth double checking",
    "I do not follow the logic here",
    "I think you are missing a key piece of the picture",
    "That point is more complicated than you make it seem",
    "This claim requires more evidence",
    "I would argue the opposite",
    "This conclusion seems premature",
    "There are some assumptions here worth examining",
    "I think this analysis is incomplete",
    "I would challenge the framing of this argument",
]

rows = [(1, t) for t in SOFT_TOXIC] + [(0, t) for t in SOFT_NONTOXIC]

# ── Round 2 — targeted patterns that were previously missed ────────────
ROUND2_TOXIC = [
    # "clown" + take patterns
    "what a clown take", "absolute clown behavior", "total clown energy",
    "what a clown response", "this is clown logic", "certified clown take",
    "clown take of the century", "that is a clown argument", "pure clown behavior",
    "this is the clowniest take", "what a clown comment", "clown tier opinion",
    "you sound like a clown", "stop with the clown takes", "clown behavior detected",
    "this is grade A clown behavior", "what a clown thing to say",
    "clown energy radiating from this comment", "peak clown behavior right here",
    "another clown showing up in the comments",

    # "nobody listens to you" patterns
    "this is why nobody listens to you", "this is why no one takes you seriously",
    "no one listens to people like you", "nobody here cares what you think",
    "this is exactly why people ignore you", "no wonder nobody takes you seriously",
    "this is why you get ignored", "people like you are why comment sections are muted",
    "you are speaking into the void", "nobody wants to hear your takes",
    "this is why everyone scrolls past your comments", "you clearly have no audience",
    "you wonder why no one engages with you seriously", "no one is buying what you are selling",
    "this explains why you have no followers", "zero people agree with you and for good reason",
    "your opinions go nowhere because they are terrible",
    "you are talking and no one is listening",
    "every single person in this thread disagrees with you",

    # "you sound clueless" patterns
    "you sound completely clueless", "you sound absolutely clueless",
    "you really sound clueless right now", "you sound uninformed",
    "you sound like you have no idea what is going on",
    "you come across as completely clueless", "you sound incredibly ignorant",
    "you genuinely have no idea do you", "you sound like someone who has never thought about this",
    "you sound like you just discovered this topic",
    "you sound like someone reading a headline and nothing else",
    "you sound hopelessly out of the loop", "you sound dangerously misinformed",
    "you sound like you are making this up as you go",
    "you really have zero clue about this topic",
    "no offense but you sound like you have no idea what you are talking about",
    "you sound lost in this conversation",
    "you clearly sound like someone who has never thought critically about this",
    "you sound like you pulled that opinion out of thin air",

    # "stop embarrassing yourself" patterns
    "stop embarrassing yourself", "please stop embarrassing yourself",
    "you need to stop embarrassing yourself", "stop embarrassing yourself online",
    "you are really embarrassing yourself right now", "just stop embarrassing yourself",
    "you are embarrassing yourself in this thread", "stop humiliating yourself publicly",
    "this is embarrassing for you", "this is so embarrassing for you",
    "i am embarrassed on your behalf", "this is genuinely embarrassing to witness",
    "please stop before you embarrass yourself more", "you are making a fool of yourself",
    "every reply is more embarrassing than the last",
    "you should stop before this gets worse for you",
    "you are actively embarrassing yourself right now",
    "the cringe is off the charts", "this level of embarrassment should be illegal",
    "you really showed everyone here who you are",

    # "laughably bad" patterns
    "that argument is laughably bad", "this is laughably wrong",
    "this is laughably incorrect", "your take is laughably off",
    "that was laughably misinformed", "this logic is laughably flawed",
    "the reasoning here is laughably weak", "this is laughably naive",
    "that conclusion is laughably wrong", "this argument is laughably easy to refute",
    "your position is laughably indefensible", "the confidence is laughable",
    "that is a laughably bad argument", "this comment is laughably bad",
    "the irony of this take is laughable", "laughably poor reasoning",
    "that is just laughably wrong on every level",
    "your logic is almost laughably bad", "this is laughably easy to disprove",
    "what a laughably weak argument",

    # group-directed insults (no slurs, just dismissal)
    "this comment section is full of idiots",
    "the people in this thread are embarrassing",
    "why are there so many braindead takes in here",
    "the collective IQ of this comment section is concerning",
    "everyone agreeing with this is wrong",
    "people like you ruin every comment section",
    "this community has some truly clueless people",
    "why do people like this exist in comment sections",
    "the amount of wrong opinions here is staggering",
    "collectively the worst takes i have seen today",

    # brain / intelligence insults
    "your brain must be on vacation", "did your brain take a day off",
    "your brain clearly needs a reboot", "brain not found",
    "you might want to let your brain warm up before commenting",
    "the neurons are not firing today are they",
    "is your brain out of office", "clearly running on empty up there",
    "the critical thinking department is closed in your head",
    "i think your brain autocorrected to the wrong conclusion",
]

ROUND2_NONTOXIC = [
    "I see your point but I think you are missing some context",
    "That is not quite right but I understand why you might think that",
    "I disagree but it is a nuanced topic",
    "I think this is more complex than a simple yes or no",
    "You might want to reconsider that based on the evidence",
    "That is an understandable conclusion but it does not hold up",
    "I have heard this argument before and I think it has some flaws",
    "That position is hard to defend with the available evidence",
    "I think you are oversimplifying a complex issue",
    "Not sure I agree but I appreciate you sharing your perspective",
    "I do not think the evidence supports that conclusion",
    "That framing is a bit off in my view",
    "I would challenge some of the assumptions here",
    "There is some merit to this but also significant issues",
    "I find this argument unconvincing but I see where you are going",
    "I would need more evidence before I could agree with that",
    "You raise a point but it is not a strong one",
    "That take is a bit of a stretch in my opinion",
    "I think you are reading into this more than necessary",
    "That reasoning does not quite follow in my view",
    "I see the logic but I think it breaks down here",
    "That is a common misconception but it is not quite accurate",
    "I respectfully think that is not right",
    "I do not share that view but I respect the discussion",
    "I think that conclusion is a bit hasty",
]

rows += [(1, t) for t in ROUND2_TOXIC] + [(0, t) for t in ROUND2_NONTOXIC]

df = pd.DataFrame(rows, columns=["Toxicity", "tweet"])
os.makedirs("model", exist_ok=True)
df.to_csv("model/synthetic_soft_insults.csv", index=False)
print(f"Saved {len(df)} rows → model/synthetic_soft_insults.csv")
print(f"  Toxic   : {df['Toxicity'].sum()}")
print(f"  Non-toxic: {(df['Toxicity']==0).sum()}")
